apiVersion: apps/v1
kind: Deployment

metadata:
  name: gemal-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gemal-dev

  template:
    metadata:
      labels:
        app: gemal-dev

    spec:
      containers:
        - name: gemal-dev
          image: 817009059025.dkr.ecr.us-east-1.amazonaws.com/gemal-dev:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080