apiVersion: apps/v1
kind: Deployment

metadata:
  name: gemal-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gemal-dev

  template:
    metadata:
      labels:
        app: gemal-dev

    spec:
      containers:
        - name: gemal-dev
          image: gemal-dev:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080