apiVersion: apps/v1
kind: Deployment

metadata:
  name: website

spec:
  replicas: 1

  selector:
    matchLabels:
      app: website

  template:
    metadata:
      labels:
        app: website

    spec:
      containers:
        - name: website
          image: 817009059025.dkr.ecr.us-east-1.amazonaws.com/gemal-world:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://website-postgres:5432/posts"

            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"